name = "Iris"
license = "MIT"
licenselink = "https://github.com/peaceiris/hugo-theme-iris/blob/main/LICENSE"
description = "Hugo Iris Theme - Portfolio and Blog"
homepage = "https://github.com/peaceiris/hugo-theme-iris"
demosite = "https://hugothemeiris.peaceiris.com/"
min_version = "0.120.0"
tags = [
  "blog",
  "responsive",
  "personal",
  "google-analytics",
  "portfolio",
  "dark",
  "disqus",
  "multilingual",
  "fast",
  "mobile",
  "syntax-highlighting",
  # "font-awesome",
  "flexbox",
  # "search",
  "presentation",
  "bulma",
  # "fontawesome",
  "netlify",
  "slide"
]
features = [
  "mathjax",
  "mermaid",
  "reveal.js",
  # "netlify-cms"
]

[author]
  name = "peaceiris"
  homepage = "https://peaceiris.com"
