baseURL: "https://hugothemeiris.peaceiris.com"

module:
  imports:
    - path: github.com/peaceiris/hugo-theme-iris
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
    - source: node_modules/reveal.js
      target: assets/reveal.js
    - source: node_modules/hotkeys-js
      target: assets/hotkeys-js
    - source: node_modules/mermaid
      target: assets/mermaid
    - source: node_modules/mathjax
      target: assets/mathjax
    - source: node_modules/mathjax/es5/output/chtml/fonts/woff-v2
      target: static/mathjax/es5/output/chtml/fonts/woff-v2

# googleAnalytics: UA-123-45
disqusShortname: hugothemeiris

paginate: 3
canonifyURLs: true
enableRobotsTXT: true
pluralizeListTitles: false

# hugo syntax highlighting
pygmentsUseClasses: true
pygmentsCodefences: true

enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true

taxonomies: {}
#   - tag: tags

imaging:
  quality: 75

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
  tdewolff:
    xml:
      keepWhitespace: true

build:
  noJSConfigInAssets: false
  useResourceCacheWhen: fallback
  writeStats: true

# Configure Languages
DefaultContentLanguage: en
languages:
  en:
    contentDir: content/en
    languageName: English
    languageCode: en-us
    params:
      author: peaceiris
      description: Hugo IRIS Theme Demo Site
      publishdate: '2020-01-01'
      twitter:
        username: piris314
      ogp:
        siteName: Hugo Theme Iris
        image: images/ogp.jpg
        locale: en-US
    title: Hugo IRIS Theme
    weight: 1
  ja:
    contentDir: content/ja
    languageName: 日本語
    languageCode: ja-jp
    params:
      author: peaceiris
      description: Hugo IRIS テーマデモサイト
      publishdate: '2020-01-01'
      twitter:
        username: piris314
      ogp:
        siteName: Hugo Theme Iris
        image: images/ogp.jpg
        locale: ja-JP
    title: Hugo IRIS テーマ
    weight: 2
