name: Release

on:
  workflow_dispatch:
    inputs:
      semver_type:
        description: "Semver type"
        required: true
        type: "choice"
        options:
          - "patch"
          - "minor"
          # - "major"
        default: "patch"

jobs:
  main:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions: {}
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-discussions: write

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          token: ${{ steps.app.outputs.token }}
          fetch-depth: 0

      - uses: peaceiris/workflows/setup-git@f99ac413519ad25fb17bff62d8f9f5e5ca32927d # v0.21.5

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
        run: |
          CURRENT_TAG=$(git describe --abbrev=0)
          NEW_VERSION=$(npm_config_yes=true npx semver "${CURRENT_TAG}" --increment ${{ github.event.inputs.semver_type }})
          NEW_TAG="v${NEW_VERSION}"
          RELEASE_TITLE="Release ${NEW_TAG}"
          git tag -a "${NEW_TAG}" -m "${RELEASE_TITLE}"
          git push origin "${NEW_TAG}"
          gh release create "${NEW_TAG}" --title "${RELEASE_TITLE}" --generate-notes --discussion-category "Announcements"
